# Generated by Django 4.2.2 on 2023-11-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club_MMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Department',
            field=models.CharField(blank=True, choices=[('CE', 'Civil Engineering'), ('AR', 'Architect'), ('CSE', 'Computer Science and Engineering'), ('SE', 'Software Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EPC', 'Electrical Power and Control Engineering'), ('ME', 'Mechanical Engineering'), ('CH', 'Chemical Engineering'), ('MSE', 'Material Science and Engineering')], max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Year',
            field=models.CharField(blank=True, choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year'), (5, 'Fifth Year')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Phone_number',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='User_ID',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
