# Generated by Django 4.2.2 on 2023-11-23 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Club_MMS', '0002_customuser_department_customuser_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Year',
        ),
    ]
