# Generated by Django 4.2.2 on 2023-11-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club_MMS', '0003_remove_customuser_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Phone_number',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
