# Generated by Django 4.2.2 on 2023-11-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club_MMS', '0004_news_alter_customuser_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, max_length=200, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='Image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
