# Generated by Django 4.2.2 on 2023-11-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club_MMS', '0005_profileimage_alter_news_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AddField(
            model_name='event',
            name='Image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
