# Generated by Django 4.2.2 on 2023-11-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club_MMS', '0006_delete_news_event_image_alter_profileimage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Date_and_Time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='Description',
            field=models.CharField(blank=True, max_length=100000),
        ),
        migrations.AlterField(
            model_name='event',
            name='Event_type',
            field=models.CharField(choices=[('SE', 'Seminar'), ('CO', 'Conference'), ('WKS', 'Workshop'), ('HKN', 'Hackathons'), ('TTK', 'TechTalks'), ('PRS', 'Project_Showcases'), ('CDC', 'Coding Competitions'), ('CLP', 'Collaborative Projects'), ('CHE', 'Charity Events')], default='-------', max_length=15),
        ),
        migrations.AlterField(
            model_name='event',
            name='Image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
