# Generated by Django 4.2.2 on 2023-11-25 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Club_MMS', '0009_message_delete_profileimage_alter_event_event_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
