# Generated by Django 4.2.2 on 2023-11-27 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club_MMS', '0010_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 15, 59, 4, 24964, tzinfo=datetime.timezone.utc)),
        ),
    ]
