# Generated by Django 4.2.2 on 2023-11-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club_MMS', '0013_remove_event_datetime_event_today_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
