# Generated by Django 4.2.2 on 2023-11-30 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Club_MMS', '0014_specialannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialannouncement',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
